#!/bin/bash

read -p "Version: " VERSION

if [ -z "$VERSION" ]; then
    echo "No version was provided"
    exit 1
fi

STARTUP_DIR=$(pwd)

echo "Creating distributables for Xen v$VERSION"

make clean
make release
make windows-release

REL_DIR=/home/x/Code/Xen/releases/$VERSION

if [ -e "$REL_DIR" ]; then
    rm -rf $REL_DIR
fi

mkdir -p "$REL_DIR/linux"
mkdir -p "$REL_DIR/windows"

make_linux_rpm() {
    RPMBUILD_ROOT="/home/x/rpmbuild"
    LINUX_RPM_TAR="$RPMBUILD_ROOT/SOURCES/Xen-$VERSION.tar.gz"
    RPM_TMP_DIR="$RPMBUILD_ROOT/SOURCES/Xen-$VERSION"

    mkdir -p $RPM_TMP_DIR
    cp -r src examples README.md LICENSE Makefile $RPM_TMP_DIR/
    cd $RPM_TMP_DIR/../
    tar -czf $LINUX_RPM_TAR Xen-$VERSION/
    rm -rf $RPM_TMP_DIR
    rpmbuild -ba $RPMBUILD_ROOT/SPECS/xen.spec

    cd ../RPMS
    find . -name "Xen-$VERSION-*.rpm" ! -name "*debug*" -exec cp {} $REL_DIR/linux/Xen-$VERSION-linux-x64.rpm \;

    cd $STARTUP_DIR
}

make_linux_deb() {
    DEB_ROOT="$REL_DIR/linux/Xen-$VERSION-linux-x64"
    mkdir -p "$DEB_ROOT/DEBIAN"
    mkdir -p "$DEB_ROOT/usr/bin"
    mkdir -p "$DEB_ROOT/usr/share/xen/examples"
    mkdir -p "$DEB_ROOT/usr/share/doc/xen"

    cp bin/xen "$DEB_ROOT/usr/bin/"
    cp -r examples "$DEB_ROOT/usr/share/xen/"
    cp README.md LICENSE "$DEB_ROOT/usr/share/doc/xen/"
    cp specs/xen.control "$DEB_ROOT/DEBIAN/control"

    dpkg-deb --build $DEB_ROOT
    rm -rf $DEB_ROOT
}

make_linux_tarball() {
    LINUX_BIN_TAR="$REL_DIR/linux/Xen-$VERSION-linux-x64.tar.gz"
    tar -czf $LINUX_BIN_TAR bin/ examples/ README.md LICENSE
}

make_windows_zip() {
    WINDOWS_BIN_ZIP="$REL_DIR/windows/Xen-$VERSION-windows-x64.zip"
    zip -r $WINDOWS_BIN_ZIP bin_win/ README.md LICENSE
}

make_windows_exe() {
    FILENAME="Xen-$VERSION-windows-x64.exe"
    WINDOWS_EXE="$REL_DIR/windows/$FILENAME"
    (cd specs && wine64 /home/x/.wine/drive_c/Program\ Files\ \(x86\)/Inno\ Setup\ 6/ISCC.exe xen.iss)
    mv specs/$FILENAME "$REL_DIR/windows/"
}

make_source_tarball() {
    SOURCE_TAR="$REL_DIR/Xen-$VERSION.tar.gz"
    tar -czf $SOURCE_TAR src/ examples/ .clang-format README.md LICENSE Makefile
}

# Linux
make_linux_rpm
make_linux_deb
make_linux_tarball
# Windows
make_windows_zip
make_windows_exe
# Source Code
make_source_tarball

echo ""
echo "=== DONE ==="
echo "Created Xen v$VERSION"
